"""Large vocabulary pools for per-prompt hook sampling.

Kept in a dedicated module so ``trace_prompts.py`` stays focused on prompt
composition. Each pool is ~10x the previous size (targeting 100-250 entries
per abstraction level) to maximize motivation diversity across the dataset.

Organizing principle per pool:
- ``REFERENCE_HOOKS``          — records/artists/producers/engineers by name.
- ``EMOTIONAL_HOOKS``          — feeling-forward adjectives + sensations.
- ``SCENE_METAPHORS``          — everyday scenes / environments.
- ``INSTRUMENT_SPECIFIC_HOOKS``— diagnostic framings pointing at named tracks.
- ``TECHNICAL_HOOKS``          — session-note-style parametric targets.
- ``NEGATIVE_SPACE_HOOKS``     — "what you DON'T want" phrases.
"""

from __future__ import annotations


# ---------------------------------------------------------------------------
# REFERENCE_HOOKS (~230 entries) — spans eras, genres, and engineering legends
# ---------------------------------------------------------------------------
REFERENCE_HOOKS: tuple[str, ...] = (
    # Hip-hop / beat-makers
    "J Dilla's Donuts — dusty MPC drums, crooked timing, off-kilter swing",
    "Nujabes' Modal Soul — late-night jazz keys, warm head-nod drums",
    "Madlib's Shades of Blue — crate-digger jazz with boom-bap drums",
    "DJ Shadow's Endtroducing — sample-collage density, detective-film vibe",
    "A Tribe Called Quest's Low End Theory — loose drums, upright bass, warm jazz loops",
    "De La Soul's 3 Feet High — playful samples, bright snares, dusty filters",
    "Pete Rock's Main Ingredient — horn-stab loops, thick kick, airy reverbs",
    "9th Wonder's The Minstrel Show — warm vinyl loops, snappy snares",
    "MF DOOM's Mm..Food — grainy filters, bar-to-bar timbre switches",
    "Kanye West's College Dropout — soul-sample pitch-ups, punchy drums",
    "Kendrick Lamar's To Pimp a Butterfly — live jazz band with hip-hop drums",
    "Flying Lotus's Cosmogramma — glitchy jazz chaos, deep sub, strange space",
    "Black Milk's Album of the Year — tight kicks, scuffed-up snares",

    # Modern downtempo / electronic
    "Daft Punk's Discovery — filter-disco warmth, vocoder-free sections",
    "Air's Moon Safari — lush synths, wide stereo, French electronica warmth",
    "Boards of Canada's Music Has the Right to Children — sun-faded tapey synths",
    "Bonobo's Black Sands — lush downtempo, acoustic instruments with electronics",
    "Massive Attack's Mezzanine — widescreen brooding, trip-hop drums",
    "Portishead's Dummy — cinematic trip-hop, dusty breaks, sparse keys",
    "Tycho's Dive — glowing chorused guitars, patient 4/4, warm synths",
    "Four Tet's Rounds — clicky percussion, felty piano, cozy loops",
    "Jon Hopkins' Singularity — analog-warm electronica with organic motion",
    "Burial's Untrue — rain-on-pavement ambience, shuffled 2-step",
    "Blockhead's Music by Cavelight — slow, lush, nocturnal instrumental beats",

    # Rock / post-rock / shoegaze
    "Radiohead's Kid A — mid-period dread, detuned warmth",
    "Radiohead's In Rainbows — dense polyrhythmic drums, warm Rhodes-ish keys",
    "Sigur Rós' Ágætis byrjun — glacial post-rock patience, bowed guitar",
    "Explosions in the Sky's The Earth Is Not a Cold Dead Place — cavernous drums, shimmering guitars",
    "My Bloody Valentine's Loveless — melt-into-walls guitars, tape-wobble",
    "Slowdive's Souvlaki — dense delay-haze, chorused guitars",
    "Tame Impala's Currents — psychedelic swirl, compressed drums, warm bass",
    "The National's High Violet — bleary reverbs, baritone rumble",
    "Pink Floyd's Dark Side of the Moon — expansive panning, analog tape warmth",
    "Led Zeppelin IV — room-drenched drums, punchy bass, live feel",

    # Industrial / dark
    "Nine Inch Nails' The Fragile — industrial clarity, surgical low-end",
    "Aphex Twin's Selected Ambient Works Vol II — unsettling bright textures",
    "Autechre's LP5 — brittle percussion, alien sound design",
    "Godspeed You! Black Emperor's F♯ A♯ ∞ — doom-laden strings, tape saturation",

    # Jazz / fusion / crossover
    "Miles Davis' In a Silent Way — transparent, restrained, open-space jazz",
    "Miles Davis' Kind of Blue — blooming modal piano, upright bass, velvet cymbals",
    "Bill Evans Trio at the Village Vanguard — intimate room, hushed brush work",
    "Herbie Hancock's Maiden Voyage — open post-bop, warm rhythm section",
    "Alice Coltrane's Journey in Satchidananda — harp-and-drone floating jazz",
    "John Coltrane's A Love Supreme — spiritual urgency, close-miked horn presence",
    "Weather Report's Heavy Weather — bright fusion fret bass, tight claves",
    "Thundercat's Drunk — busy six-string bass, dense jazz chords",
    "Robert Glasper's Black Radio — RnB-jazz crossover, airy Fender Rhodes",

    # Classic soul / funk / R&B
    "Stevie Wonder's Talking Book — warm clavinet, live drum-room swagger",
    "Curtis Mayfield's Super Fly — silky strings, wah guitars, upright bass",
    "James Brown's Funky Drummer — tight live room, big-room snare crack",
    "Isaac Hayes' Hot Buttered Soul — orchestral layers with deep funk pocket",
    "D'Angelo's Voodoo — heavy, behind-the-beat drums, warm fat bass",
    "Erykah Badu's Baduizm — earthy drums, hushed bass, nocturnal keys",

    # Ambient / minimalism
    "Brian Eno's Ambient 1: Music for Airports — drifting piano, slow tape loops",
    "Harold Budd & Brian Eno's The Plateaux of Mirror — felted piano, long reverb tails",
    "Steve Reich's Music for 18 Musicians — pulsing marimbas, hypnotic repetition",
    "Hiroshi Yoshimura's Music for Nine Post Cards — sunlit Rhodes minimalism",
    "Nils Frahm's Spaces — intimate close-mic piano with room noise",
    "Max Richter's Sleep — slow-motion strings, patient piano",
    "William Basinski's Disintegration Loops — decaying tape, faded orchestral loop",
    "Grouper's Dragging a Dead Deer Up a Hill — cassette-haze, whispered piano",

    # 60s / 70s foundations
    "The Beatles' Sgt. Pepper's — mono-to-stereo experiments, heavy compression",
    "The Beach Boys' Pet Sounds — wall-of-sound orchestral pop arrangements",
    "Phil Spector's Wall of Sound — dense layered parts, crushed dynamics",
    "Neil Young's Harvest — room-mic acoustic guitars, tape warmth",
    "Joni Mitchell's Blue — close-miked acoustic guitar, intimate vocal space (instr. version)",
    "Bob Dylan's Blood on the Tracks — dry acoustic strum, warm upright bass",
    "Pink Floyd's Wish You Were Here — analog synth sweeps, long reverbs",
    "Fleetwood Mac's Rumours — wide stereo, compressed drums, punchy bass",
    "Steely Dan's Aja — session-player perfection, clean clear Rhodes",
    "Donald Fagen's The Nightfly — hi-fi mastering, pristine session playing",
    "Toto's IV — clinical 80s studio polish, compressed everything",
    "The Police's Synchronicity — tight small-combo rock, bright hats",

    # 80s era
    "Peter Gabriel's So — gated reverbs on drums, wide 80s stereo",
    "Prince's Sign o' the Times — LinnDrum snaps, sparse funk arrangement",
    "Kate Bush's Hounds of Love — Fairlight pads, operatic arrangement",
    "Cocteau Twins' Heaven or Las Vegas — shimmer reverbs, chorused guitars",
    "Talk Talk's Spirit of Eden — improvised, sparse, cavernous",
    "Enya's Watermark — layered synth pads, long reverbs, windswept",
    "Kraftwerk's Trans-Europe Express — clinical analog sequencing",
    "New Order's Power, Corruption & Lies — sequenced bass, dry drum machines",
    "Depeche Mode's Violator — industrial textures, wide arrangement",

    # Pop production touchstones
    "early Taylor Swift + Jack Antonoff — wide, bright, punchy pop",
    "Billie Eilish's When We All Fall Asleep — ASMR-close whispers, sub-sub bass (instr. sections)",
    "Frank Ocean's Blonde — lo-fi piano, detuned synths, close-mic guitars",
    "Bon Iver's 22, A Million — vocoder-less glitch, warm Prophet pads",
    "Fleet Foxes' Helplessness Blues — room-mic guitars, dense harmony stacks",
    "Sufjan Stevens' Illinois — layered ensemble, banjos, close-mic woodwinds",
    "Phoebe Bridgers' Punisher — spacious, restrained, mournful strings",

    # Country / Americana
    "Willie Nelson's Red Headed Stranger — sparse acoustic warmth",
    "Dolly Parton's Jolene — clean country pop, bright acoustic guitar",
    "Townes Van Zandt's Live at the Old Quarter — bone-dry, intimate room",
    "Gillian Welch's Time (The Revelator) — austere bluegrass duet, close mics",
    "Kacey Musgraves' Golden Hour — shimmering stereo, warm analog synths",

    # World / traditional crossovers
    "Paul Simon's Graceland — mbira, accordion, punchy township jive",
    "Fela Kuti's Zombie — big-room horns, loose Afrobeat percussion",
    "Ali Farka Touré's The Source — desert-blues guitar, spacious acoustic",
    "Ryuichi Sakamoto's Merry Christmas Mr. Lawrence — wistful solo piano",
    "Hiromi Uehara's Move — virtuosic piano, dynamic trio",

    # Film score / games / classical crossover
    "Joe Hisaishi scoring Studio Ghibli — orchestral warmth, pastoral mood",
    "Ennio Morricone's spaghetti-western scores — twangy guitar, whistling melody, wide reverb",
    "Bernard Herrmann's Psycho — sharp staccato strings",
    "Hans Zimmer's Interstellar — cathedral organ, massive dynamics",
    "John Williams' Jurassic Park — lush orchestral brass, wide hall",
    "Thomas Newman's American Beauty — sparse Rhodes, felted textures",
    "Jonny Greenwood's There Will Be Blood — dissonant string clusters",
    "Mica Levi's Under the Skin — alien-timbre strings, unsettling low end",

    # Latin / Brazilian / Afro-diasporic
    "Tom Jobim's Wave — soft bossa swing, warm upright bass",
    "Elis & Tom — intimate Brazilian jazz, close-mic Spanish guitar",
    "Stan Getz & João Gilberto's Getz/Gilberto — dreamy bossa, close whispered delivery (instr.)",
    "Caetano Veloso's Araçá Azul — experimental tropicalia, sparse acoustic textures",
    "Rubén Blades' Siembra — crisp salsa rhythm section",

    # Studio / engineer reference points
    "a vintage Blue Note session — Rudy Van Gelder's mics",
    "a 1960s Motown session — punchy mono feel, tambourine up front",
    "a 1970s Lee Perry dub plate — King Tubby-style mix, tape echoes",
    "a 1970s Laurel Canyon folk session — live room, close mics",
    "a 1980s Trevor Horn production — dense layers, gated reverb",
    "a modern Ricky Reed polished pop session — punchy, wide, loudness-optimized",
    "a Jack White Third Man session — analog tape, one take, minimal processing",
    "a Steve Albini Electrical Audio recording — room mics, no compression on drums",
    "a Daptone Records funk session — bone-dry room, crusted snare",

    # Lo-fi / bedroom / tape era
    "a cassette-dubbed mixtape from 1997 — warm saturated hiss",
    "a scuffed 45 rpm single played through a kitchen radio",
    "a chopped-up sample on an MPC3000, quantization turned off",
    "a 4-track Tascam demo with tape compression",
    "a Chillhop Essentials compilation — lo-fi sample flips, warm 808s",
    "a Spotify Peaceful Piano playlist target — polite, soft, space-forward",

    # Jazz pianists / solo instrumentalists (instrumental refs)
    "Keith Jarrett's Köln Concert — intimate solo piano with sustain pedal air",
    "Brad Mehldau's trio recordings — quiet-to-loud piano dynamics",
    "Chick Corea's Return to Forever — fusion Rhodes, tight bass",
    "Hiromi's Alive — energetic trio, close-mic'd everything",
    "Vijay Iyer's Accelerando — angular piano trio",

    # Contemporary electronic producers
    "Kaytranada's 99.9% — house-influenced grooves, snappy drums",
    "Disclosure's Settle — warm UK garage, punchy sub",
    "Caribou's Our Love — airy synths, laid-back programmed drums",
    "Todd Terje's It's Album Time — nu-disco, analog synth warmth",
    "Lindstrøm's Six Cups of Rebel — cosmic disco, long build-ups",
    "Toro y Moi's Underneath the Pine — chillwave haze, warm Rhodes",

    # UK bass / garage / jungle
    "Pendulum's Hold Your Colour — punchy drum-and-bass engineering",
    "Goldie's Timeless — lush drum-and-bass strings",
    "Roni Size's New Forms — intricate jungle drums, warm bass",

    # Metal / heavy genre refs
    "Metallica's Black Album — scooped mids, punchy kick, wide guitars",
    "Pantera's Vulgar Display of Power — dry drums, razor guitars",
    "Opeth's Blackwater Park — massive dynamics between clean and distorted",
    "Deftones' White Pony — dreamy harmonic parts in heavy frame",

    # Experimental / avant-garde
    "Björk's Vespertine — music-box textures, delicate beats",
    "Laurie Anderson's Big Science — dry spoken-rhythm pieces (instr. focus)",
    "Philip Glass's Koyaanisqatsi — pulsating ensemble, hypnotic",

    # K-pop / J-pop / Asia
    "early Hikaru Utada — RnB-pop with bright pop mixing",
    "YMO's Solid State Survivor — clean 80s electronic pop",
    "Cornelius' Fantasma — dense stereo experimentation",

    # RnB modern
    "The Weeknd's Dawn FM — synthwave nostalgia, mastered-loud pop",
    "SZA's Ctrl — lo-fi warm R&B, clipped drums",
    "Anderson .Paak's Malibu — live drums, warm basslines",

    # Score / games (more)
    "the opening cue of Blade Runner 2049 — wall-of-sound synth swells",
    "the Grand Theft Auto Vice City radio aesthetic — 80s FM polish",
    "a Studio Ghibli end-credits cue — lush orchestra with warm reverb",
    "a Persona 5 Royal battle track — acid-jazz keys, walking bass",
    "a Monkey Island port-town theme — Caribbean synth, warm ambience",
    "a Chrono Trigger forest theme — SNES polyphony, bright chorus",

    # Reggae / dub
    "Lee Perry's Upsetters — space-echo-drenched dub",
    "Augustus Pablo's King Tubbys Meets Rockers Uptown — melodica, deep dub bass",
    "Burning Spear's Marcus Garvey — tight rhythm section, horn stabs",

    # House / techno
    "Larry Heard's Mr. Fingers — deep, warm Chicago house",
    "Theo Parrish's Sound Signature cuts — sampled, hypnotic, raw",
    "Floating Points' Crush — analog warmth, gradual builds",
    "Actress' Ghettoville — saturated, blurred textures",
)


# ---------------------------------------------------------------------------
# EMOTIONAL_HOOKS (~150 entries)
# ---------------------------------------------------------------------------
EMOTIONAL_HOOKS: tuple[str, ...] = (
    "warm and nostalgic, like stepping into a memory you can't quite place",
    "claustrophobic and tense, something about to break",
    "expansive and euphoric, that last-chorus-at-a-festival lift",
    "melancholic and reflective, rainy-window Sunday morning",
    "intimate and confessional, 3am confession in a dim room",
    "dreamy and unhurried, half-asleep in a moving train",
    "aggressive and urgent, a chase scene without dialogue",
    "elegant and restrained, a jewel in a velvet box",
    "eerie and disquieting, something wrong just out of frame",
    "lush and romantic, candle-lit and unashamed",
    "sparse and brutalist, every element doing exactly one job",
    "hypnotic and circular, losing track of time",
    "dusty and gritty, pulled out of a forgotten crate",
    "hazy and psychedelic, edges melting into each other",
    "cinematic and widescreen, opening credits of something important",
    "punchy and immediate, front-row energy, no distance",
    "cold and detached, looking at yourself from above",
    "defiant and celebratory, joy with teeth",
    "delicate and glassy, about to shatter if nudged",
    "boisterous and rowdy, a kitchen party at full tilt",
    "somber and contemplative, walking a cemetery at dusk",
    "sinister and smirking, a villain enjoying themselves",
    "yearning and unresolved, a question never answered",
    "weightless and airborne, clouds parting at altitude",
    "jagged and edgy, broken glass on concrete",
    "plush and velvet, silk sheets in a sunlit room",
    "tight and clenched, fist ready to unclench",
    "loose and drunken, last dance of the night",
    "ghostly and half-there, half a thought in a dream",
    "buoyant and bouncing, kids on a trampoline",
    "feverish and delirious, a cold medicine hallucination",
    "regal and stately, a slow procession",
    "pensive and quiet, a diary being written",
    "restless and pacing, waiting for bad news",
    "playful and elastic, a balloon being batted around",
    "solemn and ceremonial, a candle being lit",
    "snapping and biting, a dog guarding its yard",
    "radiant and glowing, afternoon light on wood floors",
    "chilly and austere, an empty church in January",
    "sticky and humid, a southern summer evening",
    "crystalline and bright, ice cubes in a glass",
    "smoky and low-lit, a jazz club at 1am",
    "wiry and nervous, a second cup of coffee too much",
    "lumbering and heavy, a forgotten giant waking up",
    "crisp and bracing, the first cold day of autumn",
    "decadent and indulgent, a chocolate-cake-for-breakfast move",
    "brittle and fragile, cracked porcelain",
    "muscular and strutting, confidence without bluster",
    "wistful and faded, an old photograph in a drawer",
    "mechanical and ticking, watchwork in motion",
    "grubby and worn-in, a favorite pair of boots",
    "lush and tropical, bougainvillea in June",
    "austere and monastic, a chanted morning prayer",
    "buoyant and cocky, a swagger walking into a room",
    "unhurried and patient, a slow exhale",
    "anxious and shivery, a telephone about to ring",
    "serene and glassy, a still lake at dawn",
    "sparkling and effervescent, champagne being poured",
    "muddy and primordial, a swamp at midnight",
    "restless and thrashing, insomnia at 4am",
    "ceremonial and dignified, a long handshake",
    "dopey and content, a cat in a sunbeam",
    "harried and breathless, late for a train",
    "sun-bleached and washed-out, a beach in August",
    "velveteen and purring, a cocktail lounge after midnight",
    "electric and crackling, a storm rolling in",
    "paper-thin and fragile, origami under breath",
    "clanking and industrial, machinery grinding late-shift",
    "drowsy and post-nap, Sunday afternoon haze",
    "starlit and vast, looking at the sky in the desert",
    "tactile and hand-made, kneaded dough texture",
    "febrile and twitchy, caffeine overdose",
    "slow-burning and smoldering, embers in a fireplace",
    "hungover and blurry, the morning after",
    "choral and communal, a church full of voices (but instrumental)",
    "cackling and unhinged, laughter in an empty house",
    "swooning and lovesick, a first dance",
    "purring and feline, something prowling softly",
    "vaulted and cathedral-high, a basilica interior",
    "tight-wound and spring-loaded, a trap about to snap",
    "syrupy and slow, honey dripping off a spoon",
    "sharp and bladed, a knife edge catching light",
    "bashful and reticent, eyes down in conversation",
    "dignified and weathered, a sea captain's hands",
    "saline and brackish, rain hitting the ocean",
    "incandescent and hot, a tungsten bulb about to blow",
    "pearlescent and iridescent, oil on water",
    "frostbitten and stinging, a January windstorm",
    "confidential and whispering, a secret between friends",
    "ropey and sinewy, a climbing rope under load",
    "static and standing, a dust devil that won't move",
    "downcast and minor-key, a rainy Tuesday",
    "leering and mischievous, a trickster figure",
    "unadorned and simple, bread and butter",
    "cavernous and echoing, a cathedral whisper",
    "beatific and blissful, a saint's calm smile",
    "starchy and pressed, a crisp white shirt",
    "tarnished and patinated, antique brass",
    "jangling and loose-change, coins in a pocket",
    "cloudless and dazzling, noon sun overhead",
    "feathered and down-light, a pillow hitting a bed",
    "steely and resolute, a soldier's walk",
    "hushed and library-quiet, a study at midnight",
    "biting and astringent, lemon rind in the mouth",
    "mossy and verdant, a forest floor in spring",
    "dented and beloved, a well-used favorite",
    "lacquered and brittle, a glossy veneer",
    "fibrous and ropy, handmade rope texture",
    "clean and laundered, fresh sheets scent",
    "smoked and cured, lapsang souchong tea",
    "mellow and fermented, a bottle opened too long",
    "stained and well-used, the good coffee mug",
    "antique and well-kept, a carefully curated museum",
    "woolly and crackling, wool socks on a cold floor",
    "buttery and rich, a brown butter sauce",
    "husky and low-voiced, late-night radio host",
    "giddy and carbonated, opening a soda",
    "silvery and pinging, ice in a metal tin",
    "sooty and charred, a fireplace the next morning",
    "golden-hour and slanted, magic-hour light",
    "shuffling and reluctant, a tired afternoon",
    "pavement-hot and shimmering, a highway in July",
    "lacy and fine, frost on a window",
    "crumbly and earthy, good soil in hand",
    "vaulted and soaring, a Gothic interior",
    "blustering and bluffing, someone posturing",
    "squinting and bright, unprepared for the sun",
    "burred and rough, a peach pit",
    "saturated and spilling, an overflowing cup",
    "mottled and dappled, sunlight through leaves",
    "fragrant and herbal, a kitchen garden",
    "molten and flowing, lava in slow motion",
    "cracked and weathered, a favorite leather jacket",
    "iron-hot and bright, a forge at work",
    "shuttered and interior, rainy-day indoor light",
    "opened-up and panoramic, a vista after a long hike",
    "purged and cleansed, the first morning after a storm",
    "embered and sustained, a campfire going out slow",
    "glinting and pinprick, stars at high altitude",
    "squeezed and compressed, packed into a small room",
    "unfettered and sprawling, an empty interstate",
    "creamy and emulsified, a perfect sauce",
    "bristled and prickly, a hedge of thistle",
    "sleek and laminated, a glossy magazine cover",
    "rumpled and slept-in, a well-loved bed",
    "hollowed and cored, the aftermath of something",
    "ascending and climbing, a stairway in a tower",
    "descending and burrowing, moving deeper underground",
    "stretched and taut, a drumhead about to be struck",
)


# ---------------------------------------------------------------------------
# SCENE_METAPHORS (~200 entries)
# ---------------------------------------------------------------------------
SCENE_METAPHORS: tuple[str, ...] = (
    "like the band is playing in the next apartment, walls between us",
    "like sitting in a basement at 2am with one lamp on",
    "like a vintage radio on a dusty kitchen counter",
    "like a car driving away slowly at dusk",
    "like a faded photograph of a summer afternoon",
    "like walking into a jazz club just as the last song starts",
    "like a cathedral organ heard from the back pew",
    "like a jukebox across a crowded room",
    "like listening on your parents' stereo through the floor of your bedroom",
    "like a swimming pool at night, everything underwater but clear",
    "like driving through fog with the high beams on",
    "like tape hiss on a beloved mixtape from high school",
    "like a thunderstorm at the end of a long humid day",
    "like the sound check before the crowd arrives",
    "like an orchestra rehearsing in an empty theater",
    "like the band is in a cardboard box — way too small, everything boxy",
    "like a late-night FM DJ fading into the next song",
    "like walking into your grandmother's living room, slightly worn furniture",
    "like a snow globe shaken — tiny, contained, beautiful",
    "like someone humming to themselves in the next room",
    "like a movie score cue, wide and impersonal",
    "like a field recording on a warm afternoon",
    "like a concert hall's pre-show murmur settling",
    "like a record store on a rainy Saturday",
    "like the last song at a wedding reception",
    "like a waiting room with muzak in the ceiling",
    "like looking through a screen door at a party",
    "like a busker heard from two blocks away",
    "like an attic with boxes of old records",
    "like a train approaching from far down the track",
    "like fireworks heard from indoors",
    "like a hotel hallway at 1am — distant TVs, humming ice machines",
    "like a passing ice cream truck",
    "like a warm car interior on a cold night",
    "like someone practicing scales in the apartment above",
    "like a toy piano in a sunlit nursery",
    "like a phone call from overseas with a slight delay",
    "like a children's playground just after school lets out",
    "like a submarine sonar ping in deep water",
    "like a rotating fan blowing past a microphone",
    "like an old film projector clicking in the background",
    "like a busy airport terminal at dawn",
    "like an empty mall after closing",
    "like a hospital corridor with polished floors",
    "like a classroom during quiet reading time",
    "like a cowboy bar with a live band in the corner",
    "like a crowded subway car at rush hour",
    "like a lighthouse keeper's quarters",
    "like a desert highway at high noon",
    "like a Victorian sitting room with a grandfather clock",
    "like a ski lodge after a day on the slopes",
    "like a greenhouse with dripping leaves",
    "like a surgery room's fluorescent hum",
    "like a Catholic funeral procession",
    "like a protestant Sunday morning service",
    "like a bodega at 2am — low hum of refrigerators",
    "like a diner at 3am with chrome and neon",
    "like a submarine's interior hum",
    "like a lumberyard in morning light",
    "like a fish market just before sunrise",
    "like a wine cellar with stone walls",
    "like a darkroom under a red safelight",
    "like a movie theater five minutes before showtime",
    "like a planetarium during a light show",
    "like a mountain hut during a blizzard",
    "like an old library with tall wooden shelves",
    "like a small chapel with candles lit",
    "like a university dining hall mid-afternoon",
    "like a train station's PA announcing delays",
    "like a hotel bar at happy hour",
    "like a poolside in Havana at sunset",
    "like a Berlin club at 8am, the crowd thinning",
    "like a Tokyo alley at 10pm with softly glowing signs",
    "like a Paris café in autumn rain",
    "like a beach shack with a tin roof",
    "like an abandoned gas station in the desert",
    "like a gondola cable car at night",
    "like a boxing gym between rounds",
    "like a woodworking shop, sawdust in the air",
    "like an old racetrack after the last horse",
    "like a drive-in movie, sound coming through a tinny speaker",
    "like a record being played at 33rpm when it should be 45",
    "like a radio slowly losing signal",
    "like a brass band heard from a parade route",
    "like a church basement before bingo night",
    "like a sushi counter with quiet knife-work",
    "like an apiary in late spring",
    "like a sleeper train rocking through a valley",
    "like a ferry crossing at fog-dawn",
    "like a concert heard from a parking lot",
    "like an elevator lobby with polished marble",
    "like a barber shop with vinyl chairs",
    "like a basement jam session with chairs pushed aside",
    "like a hot-air balloon drifting at dawn",
    "like a cold garage in winter, door cracked open",
    "like a TV in the next room you're half-listening to",
    "like a party downstairs while you're trying to sleep",
    "like a stranger's house where everyone's welcome",
    "like a warehouse with corrugated metal walls",
    "like a ferry horn over a calm bay",
    "like a small-town parade from the sidewalk",
    "like a monsoon's first drops hitting a zinc roof",
    "like a sleigh in snow, bells muffled",
    "like a bakery at 4am with ovens running",
    "like a 3am bus station with vending-machine hum",
    "like a New Year's Eve countdown from miles away",
    "like a museum at closing time, empty rooms ringing",
    "like a car wash — water curtain all around",
    "like the wind through telephone lines",
    "like a radio-controlled plane buzzing overhead",
    "like a marching band on a distant football field",
    "like a dentist's waiting room with soft radio",
    "like a farmer's market winding down",
    "like a cathedral's bells from across town",
    "like a cruise ship's lounge at dinner",
    "like a taxi at idle in traffic",
    "like a backyard pool party at dusk",
    "like a grocery store after midnight",
    "like a radio checkpoint crackling on a dark highway",
    "like a fireworks finale from across a lake",
    "like an old 8mm home movie playing",
    "like a vinyl record's first crackle before the music starts",
    "like a cassette auto-reversing mid-song",
    "like an iPod headphone spill on a subway",
    "like a vinyl skipping lightly at the end",
    "like a car passing with the bass thumping",
    "like a birthday-candle moment going hushed",
    "like a plane's cabin descending into a new city",
    "like a hotel pool with no one there",
    "like a motel neon sign buzzing",
    "like a lantern swinging on a back porch",
    "like a phone booth in rain",
    "like a campfire catching, newspaper crumpling",
    "like a foghorn threaded through the night",
    "like a barn at first light with livestock moving",
    "like a milling flour house",
    "like a dry stream bed in August",
    "like a freshly paved road, black asphalt steaming",
    "like a gymnasium mid-school-dance",
    "like a summer camp's first-night cabin noise",
    "like a cello case popped open in a rehearsal room",
    "like the hush after a gavel hits",
    "like a racing pit stop, tools on ground",
    "like a bonfire burning down at 3am",
    "like a ferry's last departure of the night",
    "like a quiet village square at siesta",
    "like a packed stadium holding its breath",
    "like a ski-lift creaking upward in mist",
    "like a garage band through a thin wall",
    "like a honky-tonk piano in a saloon",
    "like a monastery's chant echoing in stone",
    "like a dive bar's last call",
    "like a church organ with a head cold",
    "like an old radio with a loose antenna",
    "like a paper cup telephone across a yard",
    "like a porch rocking chair at dusk",
    "like a taxi radio in a rainy city",
    "like a night-market's string lights",
    "like a truck stop cafe at 3am",
    "like a hospital room with a radio on low",
    "like a locker room after the game",
    "like a glass elevator going up a skyscraper",
    "like a Cold War bunker radio",
    "like a flea market's jumble on a Saturday",
    "like a vintage boutique's record player",
    "like a skate park at golden hour",
    "like a laundromat at midnight",
    "like an abandoned amusement park at dawn",
    "like a lifeguard chair at sunset",
    "like a shoeshine stand with classic jazz",
    "like a gondolier's boat gliding through Venice canals",
    "like a dim sum hall mid-brunch",
    "like a Shinto shrine at early morning",
    "like a roadside motel off Route 66",
    "like a polaroid developing in your palm",
    "like a frozen pond holding weight",
    "like a bathhouse's echoing tile",
    "like a cathedral's pre-service quiet",
    "like a glass-bottom boat over coral",
    "like a cave with a dripping stalactite",
    "like a tugboat guiding a freighter",
    "like a lecture hall's back row murmur",
    "like a thrift shop's organ section",
    "like a drum circle on a public beach",
    "like a greenhouse at noon, humid and sunny",
    "like a blizzard heard from a cabin",
    "like a midnight diner with a pie case",
    "like a cattle ranch at dawn",
    "like a train yard where cars couple and uncouple",
    "like a fishing pier at low tide",
    "like a public pool on a windy day",
    "like an old jukebox with a sticky 45",
    "like a bowling alley at midnight",
    "like a dockside bar with creaking boards",
    "like a zoo aviary filling with dusk calls",
    "like a town square fountain at night",
    "like a country church's funeral hymn",
    "like a marching band rehearsing in a gym",
)


# ---------------------------------------------------------------------------
# INSTRUMENT_SPECIFIC_HOOKS (~80 entries)
# ---------------------------------------------------------------------------
INSTRUMENT_SPECIFIC_HOOKS: tuple[str, ...] = (
    "the loudest track is dominating and needs pulling back",
    "two tracks are fighting in the midrange",
    "one track feels too bright compared to the others",
    "one track needs more weight/presence",
    "one track is sitting too far forward",
    "one track could use a character treatment (saturation / filter)",
    "the rhythm section isn't locking tightly enough",
    "one track feels too clean vs the others",
    "the kick and bass are arguing at 60–80 Hz",
    "one track is poking into the 2–4 kHz lead zone",
    "a melody element is getting buried by rhythmic clutter",
    "the low end feels flubby and undefined",
    "one track has no stereo interest — collapsing the image",
    "the attack transients on one track need to punch through more",
    "one track is too saturated / too edgy for the mood",
    "the articulation on one track is too stiff / too quantized",
    "one track has dead spots where another track would fill well",
    "the harmonic register of two tracks overlaps uncomfortably",
    "one track's sustain is too long and blurring subsequent hits",
    "one track is panned hard when it should be centered",
    "the pick attack on a string track is obnoxious",
    "one track is swamping 200–300 Hz and making the mix muddy",
    "one track has too much 5–7 kHz sibilance for an instrumental bed",
    "one track reads as a layered chord when it should be a single voice",
    "the release tails are blending into the next measure and smearing",
    "one track's velocity range is too narrow — feels mechanical",
    "a track is over-quantized, losing its human feel",
    "two tracks are playing at the same pitch class, phasing",
    "one track's low-mid body steps on the bass's fundamental",
    "a lead voice is too recessed compared to the rhythm bed",
    "the mix lacks a track in the 500 Hz — 1 kHz midrange body",
    "one track feels too dry against the others' reverb tails",
    "the percussion has no high-end sparkle",
    "one track is masking another in the 3 kHz presence region",
    "there's an imbalance between the rhythm section and the lead voices",
    "one track has weird overtones that aren't gelling with the harmony",
    "the stereo width is uneven — one side is heavier",
    "a track is too aggressive in its attack character",
    "one track needs a gentler articulation for the section",
    "one track is eating the low-mid thickness, needs thinning",
    "the pick / plectrum attack needs softening",
    "a drum element is pushing forward too much",
    "one track's reverb tail is spilling into other elements",
    "a sustained track is phasing with another sustained track",
    "the ride/hats need to sit further back in the mix",
    "the snare is too tight / too loose for the groove",
    "the kick has no definition in the sub region",
    "one voice is stepping on the lead's fundamental range",
    "the bass and kick are competing for the same transient window",
    "one track's texture is too dense for the arrangement",
    "an instrument is peaking too brightly on sustained notes",
    "a track has inconsistent dynamics across phrases",
    "one track is too quiet to carry its intended role",
    "one track is carrying too much melodic weight — overcrowded",
    "a pad track needs more motion to feel alive",
    "two melodic lines cross in the same octave register",
    "one track's stereo treatment is monoing problematic frequencies",
    "a track's tone is fighting the drum bus character",
    "one track's compression is uneven phrase-to-phrase",
    "a sustain is drowning the attack of a subsequent note",
    "the left-right image is heavier on one side",
    "the drum tail is too dry given the reverb on melodic parts",
    "one track's EQ pushes the air frequencies too aggressively",
    "the sustain of one voice is tailing into a new chord",
    "a section has too many melodic layers in one register",
    "one track is too scooped in the midrange",
    "one track is too cluttered with harmonics / partials",
    "a rhythmic accent is landing on the wrong beat",
    "the humanization feels too robotic despite timing offsets",
    "one track has mechanical sustain where breath would help",
    "a pad is competing with lead melodic motion",
    "the groove feels stiff — the drums need push or pull",
    "one track is too broad in the low end and eating the subs",
    "the stereo spread is too narrow for the genre",
    "one track's articulation is too legato for the feel",
    "the piano sustain is smearing chord changes",
    "the hat pattern is too busy and crowding other elements",
    "the guitars are too processed for this mood",
    "one track is absorbing too much of the reverb send",
)


# ---------------------------------------------------------------------------
# TECHNICAL_HOOKS (~160 entries)
# ---------------------------------------------------------------------------
TECHNICAL_HOOKS: tuple[str, ...] = (
    "target -14 LUFS integrated, -1 dBTP ceiling",
    "target -10 LUFS integrated for club-playback loudness",
    "target -16 LUFS integrated for podcast-bed loudness",
    "HPF at 40 Hz, broad -3 dB cut at 250 Hz Q 1.0",
    "HPF at 80 Hz on non-bass stems, -4 dB @ 400 Hz narrow Q",
    "HPF at 120 Hz on the hats to kill kick bleed",
    "4:1 compression threshold tickling -18 dB, attack 10 ms release 80 ms",
    "6:1 compression threshold -22 dB, attack 3 ms release 40 ms on drums",
    "3:1 soft-knee compression on the bass bus, 6 dB GR",
    "short plate reverb, pre-delay 15 ms, decay 1.8 s, HPF'd at 400 Hz",
    "long plate reverb, 3.2 s decay with pre-delay 25 ms on the pads",
    "spring reverb emulation on guitars, 700 ms decay",
    "+2 dB shelf at 80 Hz, -1 dB peak at 3.5 kHz Q 1",
    "+3 dB shelf at 120 Hz, -2 dB notch at 4 kHz Q 2",
    "parallel compression bus, 6:1 ratio, blend back at -3 dB",
    "parallel saturation bus, tape-style drive, blend at -6 dB",
    "stereo widener on the pads at 1.4, keep rhythm section mono",
    "stereo widener at 1.6 on strings, keep bass & kick mono",
    "sidechain the pad to the kick, 80 ms release",
    "sidechain the strings to the snare, 120 ms release",
    "glue bus comp 2:1, 1-2 dB gain reduction, slow attack",
    "glue bus comp 1.5:1, 6 ms attack, 80 ms release, barely tickling",
    "tape saturation at 0.15 drive on bass only",
    "tape saturation at 0.25 drive on drum bus",
    "high-shelf boost 2 dB at 10 kHz on cymbals",
    "high-shelf boost 3 dB at 12 kHz on overheads for air",
    "narrow-Q notch at 400 Hz on guitars to kill boxiness",
    "narrow-Q notch at 800 Hz on piano to reduce honk",
    "RMS target -18 dB on individual stems, -10 on the master",
    "RMS target -20 dB on stems, -12 on the full mix",
    "lowpass 8 kHz on the strings to sit behind the piano",
    "lowpass 6 kHz on organs to de-claw the harmonica register",
    "transient shaper +3 dB attack on snare",
    "transient shaper -2 dB sustain on the kick for tighter groove",
    "subtle chorus 0.3 Hz 2 ms depth on the keys",
    "chorus 0.5 Hz, 4 ms depth on pads for motion",
    "short slapback echo 120 ms 25% wet on the guitar",
    "dotted-eighth delay 375 ms, 40% wet on the lead line",
    "RIAA playback curve emphasis",
    "deesser at 6 kHz Q 4, -4 dB threshold",
    "de-muddy sweep: -3 dB 250 Hz Q 1.2 on guitar bus",
    "presence bump: +2 dB 3 kHz Q 0.8 on lead line",
    "low shelf cut: -2 dB below 100 Hz on guitars",
    "high shelf boost: +1.5 dB above 8 kHz on drum overheads",
    "multiband comp: 3:1 on low band (50-200), 2:1 mid (200-2k), 1.5:1 high (2k+)",
    "gate on tom bus, -40 dB threshold, 50 ms release",
    "master bus comp at 1.5:1, 6 dB threshold, 10 ms attack",
    "limiter ceiling at -1 dBTP, true-peak mode, 2 ms lookahead",
    "match EQ to reference track in 200 Hz – 6 kHz band",
    "tilt EQ -1 dB above 2 kHz for warmer tone",
    "tilt EQ +1.5 dB above 3 kHz for modern pop brightness",
    "DC filter at 20 Hz, slope 24 dB/oct",
    "low cut at 30 Hz on the whole mix bus",
    "low cut at 50 Hz on all non-bass stems",
    "spread the mid bus 10% wider, mono below 120 Hz",
    "haas delay 18 ms on one guitar for width",
    "mid/side EQ: +2 dB 10 kHz on sides only",
    "mid/side EQ: -1 dB 250 Hz on sides",
    "tape wow-flutter emulation, 0.4% depth",
    "analog-console emulation, saturation at unity",
    "drum parallel crusher, bitcrush at 9 bits, blend -12 dB",
    "upward expansion on bass, +2 dB at -30 dB threshold",
    "downward expansion on hats, -4 dB at -42 dB threshold",
    "SSL-style compression on drum bus, 4:1 with fast auto-release",
    "1176-style compression on the lead voice, all-buttons-in mode",
    "LA-2A-style compression on bass, slow attack, musical release",
    "Fairchild-ish gentle compression on mix bus, 1.5 dB GR",
    "Neve 1073-style EQ: +2 dB shelf at 12k, +2 dB peak at 220",
    "API 550-style EQ: proportional-Q peaks, punchy",
    "Pultec trick: boost and cut 100 Hz simultaneously",
    "mid-side compression: compress sides harder than mid",
    "vocal rider-style automation on the lead instrument",
    "dynamic EQ at 2.5 kHz, -3 dB when signal exceeds -20 dB",
    "harmonic exciter 15% mix on the high band (4-10 kHz)",
    "saturation on sides only, 10% drive",
    "parallel exciter, 20% blend, brightens the mix",
    "tape-bias tilt: more saturation in low mids, less in highs",
    "BBE-style treble enhancer, 2 dB of 8 kHz boost",
    "noise gate at -50 dB, fast 1 ms attack, 100 ms release",
    "expander on ride at 2:1, -35 dB threshold",
    "distortion with post-HPF at 200 Hz to keep low end clean",
    "soft clipper 0.2 drive, 2% total THD",
    "2-knee compression: 3:1 up to -6 dB GR, then 10:1 above",
    "LPF ramp: cutoff 20 kHz → 6 kHz over 4 bars for filter sweep",
    "HPF ramp: cutoff 20 Hz → 400 Hz over 8 bars for filter riser",
    "pitch-correct the bass to A=440 Hz reference",
    "tape delay 1/4 note synced to tempo, feedback 35%",
    "ping-pong delay 1/8 dotted, both sides 30% wet",
    "reverse reverb, 1.5 s pre-delay, 50% wet",
    "gated reverb on the snare, 300 ms gate close",
    "chamber reverb emulation, 2.4 s decay, 20% wet",
    "hall reverb, 3.8 s decay, 80 ms pre-delay, -12 dB return",
    "room reverb, 0.8 s decay, 10 ms pre-delay on drums",
    "plate reverb with 6 kHz high damping",
    "slap delay 90 ms, feedback 10%, on the snare",
    "quarter-note delay at 120 BPM (500 ms), feedback 40%",
    "triplet feel delay at 375 ms on lead",
    "convolution reverb from a church IR, 4 s tail, 15% wet",
    "vintage plate from EMT-140 sim, 2 s decay",
    "natural room from 20x15 foot space, 0.3 s RT60",
    "brickwall limiter with 1 dB GR on master",
    "clipper -0.5 dB ceiling, 2 dB of clip",
    "gentle tape saturation with 0.5 dB boost at 40 Hz and 10 kHz",
    "high-pass sweep riser, 20 Hz to 1 kHz over 8 bars",
    "low-pass sweep, 20 kHz to 2 kHz over 4 bars",
    "widener that only affects above 300 Hz, keep below mono",
    "bass mono below 120 Hz, widened above",
    "2-band exciter: low-band warmth, high-band air",
    "spring reverb with 150 ms pre-delay on guitars",
    "tape slap: single repeat at 160 ms, 60% wet",
    "short room ambience on everything, shared bus, 0.5 s decay",
    "tuned room correction: cut 80 Hz on bus (-2 dB Q 2)",
    "pink noise reference level at -20 dBFS RMS",
    "sine sweep test: confirm flatness 20 Hz - 20 kHz",
    "K-14 metering target for master",
    "K-20 metering target for audiophile mix",
    "lookahead peak limiter, 5 ms, -0.3 dBTP ceiling",
    "brickwall limiter with 2 dB of reduction on quiet passages",
    "saturation stage before limiter, 6% THD",
    "tape slap and short spring together on vocals (on the lead instrument)",
    "chorus + short delay combo for motion on the pad",
    "1-band dynamic compressor at 2 kHz, -4 dB threshold",
    "multi-stage drive: 1% tube, 1% tape, 1% solid-state, stacked",
    "harmonic saturator at 10% mix on the whole drum bus",
    "notch out 120 Hz hum, Q 30",
    "notch out 60 Hz hum on sensitive stems",
    "transient designer +4 dB attack, -1 dB sustain on drums",
    "clipper before limiter to shave transients, then gentle limit",
    "upward limiter (puts noise floor up) to push quiet parts forward",
    "envelope follower modulating filter cutoff on bass",
    "side-chain ducker on pads, triggered by drums, 0.4 ratio",
    "reverse reverb swell into each downbeat, 1 s pre-delay",
    "granular delay on lead, 50% wet, 1/16 grains",
    "bit-crush at 8 bits with 20 kHz downsample on percussion",
    "phaser with 4 stages, 0.3 Hz, 70% feedback on organ",
    "flanger with 3 ms depth, 0.2 Hz, 60% feedback on guitar",
    "tremolo 5 Hz, 40% depth on Rhodes",
    "vibrato 6 Hz, 20 cents depth on the melodic lead",
    "bus compression only above 1 kHz with a sidechain HPF",
    "parallel distortion on drums, 1% blend, subtle harmonics",
    "saturation only on the mid channel of the mid/side split",
    "exciter boosted 4 dB at 8 kHz with 15% mix",
    "gentle 2 dB presence boost at 2 kHz with Q 0.5 on the bus",
    "-3 dB low shelf below 100 Hz on the reverb return",
    "-2 dB high shelf above 8 kHz on the reverb return",
    "ducking reverb return with sidechain from dry signal",
    "short reverb pre-delay (10 ms) + long reverb tail (3 s) combo",
    "stereo spread increase at higher frequencies only",
    "Pultec-style low boost 60 Hz with cut at 60 Hz — punch trick",
    "dynamic EQ pull at 250 Hz only when signal exceeds -15 dB",
    "compression with sidechain HPF at 120 Hz, 4:1 ratio",
    "saturation with sidechain HPF at 200 Hz (only drive mid+high)",
    "mid band boost +1 dB at 2 kHz with wide Q",
    "intelligent EQ matching to a reference mix, 200 Hz — 10 kHz band",
)


# ---------------------------------------------------------------------------
# NEGATIVE_SPACE_HOOKS (~150 entries)
# ---------------------------------------------------------------------------
NEGATIVE_SPACE_HOOKS: tuple[str, ...] = (
    "but DO NOT make it sound too polished — it should still have grit",
    "but NO added reverb — it already has too much space",
    "avoid the low-end boom, we want tight not fat",
    "keep it simple, don't over-process",
    "no bright harshness — stay dark",
    "don't let anything dominate — the mix should feel balanced, not showy",
    "avoid pumping from heavy compression",
    "no vintage simulation — we want modern clarity",
    "don't crush the dynamics, keep it breathing",
    "avoid anything that sounds obviously digital",
    "nothing that screams 'mixed-in-a-bedroom' — keep it professional but warm",
    "don't let the drums dominate, they're meant to support",
    "nothing sample-chain heavy — organic feel",
    "avoid the piano sounding boxy",
    "keep the stereo image natural, not hyped",
    "don't make it too loud — clip-safe please",
    "avoid the 'pop mix' brightness — soften the top",
    "no hyped-up low end — just honest bass",
    "don't over-compress, leave the micro-dynamics",
    "nothing cartoonish — subtle is key",
    "no AI-slick smoothness — leave human imperfection",
    "avoid a karaoke-bed feel — the mix should have real presence",
    "no phase-shifty widener — keep mono compatibility intact",
    "don't let the reverb muddy the arrangement",
    "no tail-smear from long decay times",
    "avoid an ultra-hi-fi 'audiophile' vibe — this should be warm, not sterile",
    "no in-your-face brightness — this is a background bed",
    "don't let any single moment become 'the hook' — even texture",
    "avoid mp3-collapsed highs",
    "nothing so slick it feels like an AI demo",
    "no radio-ready loudness — keep it DR10+",
    "avoid 'cinematic' trailer grandeur — intimate scale",
    "don't force 4-on-the-floor — the groove should breathe",
    "no tidy pop-mastered vibe — keep it raw",
    "avoid a LUFS crush at the expense of punch",
    "don't ghost the room — leave some ambient pickup",
    "no sparkle-exciter on cymbals — natural only",
    "avoid that 'guitars-center-stage' thing — this is a bed, not a feature",
    "don't pan hard — keep it spread but centered",
    "no sidechain pumping in the bass",
    "avoid the 'everything in a box' 80s feel",
    "no reggae space delay — straight and grounded",
    "don't lean on reverb for the emotion — let dryness carry it",
    "avoid the lo-fi crackle trope — this is a different kind of warm",
    "don't layer too many things — each element earns its place",
    "no trap-hats subdivision — we're not in that lane",
    "avoid the 'Berghain' kind of extreme compression",
    "don't bring the mids forward too much — midrange fatigue",
    "no jumpy transients — smooth attacks",
    "avoid digital aliasing artifacts",
    "no hyped presence at 3 kHz",
    "don't make the piano sound like a pop record — no HPF it out",
    "avoid obvious 'Logic default' sounds",
    "don't let the stereo bus exceed 1.2× width",
    "no hint of autotune or pitch-correction anywhere",
    "avoid 1980s gated reverb on snare",
    "don't let the drums dictate the stereo image",
    "no over-polished 'podcast studio' cleanliness",
    "avoid chorus on everything — that's too 80s",
    "don't crush the dynamic range below 8 dB",
    "no surface noise unless intentional",
    "avoid the 'home-studio boxy' midrange",
    "no doubled tracks — keep everything mono and present",
    "don't stack effects on top of effects",
    "avoid any Waves-plugin 'tutorial sound'",
    "don't limit the master until the very last step",
    "no brightness bumps above 12 kHz",
    "avoid chorused guitars — clean and dry please",
    "don't over-widen — mono compatibility first",
    "no comb-filtering from stacking similar tracks",
    "avoid distortion artifacts on quiet passages",
    "don't let the bass run away into sub territory",
    "no low-mid mud below 300 Hz",
    "avoid a wall-of-sound effect — leave air between elements",
    "don't add any effect that doesn't serve the mood",
    "no over-processed 'demo-ready' clichés",
    "avoid pushing the kick too hard in the 60 Hz zone",
    "no harsh sibilance regions on cymbals",
    "don't let reverb wash overtake the dry signal",
    "avoid the 'demo reel' sheen — warmer please",
    "no 808 sub-bass replacement — honor what's there",
    "don't let any effect be obvious — all invisible production",
    "avoid that 'HD radio' hyper-clarity",
    "no over-exaggerated transient shaping",
    "don't pitch-correct the performance",
    "avoid any trace of AI mastering flatness",
    "no EDM-style buildups — steady and even",
    "don't lean into the 2 kHz presence zone",
    "avoid a 'Sunset Sound' reverb cliché",
    "no contemporary-trap distortion aesthetic",
    "don't bring the hats above -20 dBFS",
    "avoid gated reverb on any drum element",
    "no 'indie rock' bright guitar cliché",
    "don't let the bass fight the kick",
    "avoid an EQ match to any existing reference",
    "no 'Billboard loudness' limiting",
    "don't let the mids carry anxiety — soften them",
    "avoid anything that reads as 'stock preset'",
    "no over-ambient quality — ground the mix",
    "don't pump any element with sidechain compression",
    "avoid a modern pop-glaze",
    "no hyperreal 'every detail audible' processing",
    "don't let the kick poke through too much — integrated feel",
    "avoid any artifact from pitch or time stretch",
    "no phase cancellation between similar-register tracks",
    "don't over-damp the high end on the reverb",
    "avoid the 'demo mode' thinness",
    "no chunky midrange — carve it out gently",
    "don't lean into a 'Ableton default' sound",
    "avoid bass that feels rubbery / synthetic",
    "no drum samples replacing what's already there",
    "don't layer too much ambience on the lead voice",
    "avoid the 'one-take acoustic' cliché",
    "no tape simulation on everything — selective use only",
    "don't push any track into heavy distortion",
    "avoid the 'Brooklyn studio' tight-and-dry aesthetic",
    "no melancholic filter on everything",
    "don't soften the drums too much — they need some edge",
    "avoid reverb tails longer than 2 seconds",
    "no modern metal 'scooped guitars'",
    "don't pan any element fully left or right",
    "avoid any loudness war compression",
    "no click-track sterility",
    "don't add any obvious modulation effects on lead elements",
    "avoid a 'Nashville polish' — keep it rough",
    "no generic dance-mix pumping",
    "don't force a subgenre sound that doesn't fit",
    "avoid over-editing the timing — let things breathe",
    "no hi-fi 'audiophile' tolerance for silence — keep it alive",
    "don't over-emphasize any frequency range",
    "avoid processing that overshadows the musical idea",
    "no 'AI-generated ambient' smoothness",
    "don't compress the attacks into mush",
    "avoid any trace of 'preset sound'",
    "no gated drum stutter",
    "don't let the reverb dominate the front image",
    "avoid a 'podcast studio' voiceover quality",
    "no plugin watermarks on the sound",
    "don't over-balance — slight asymmetry can feel human",
    "avoid the 'bedroom producer' thinness",
    "no trap-style 808 rolls",
    "don't let any part carry visible processing",
    "avoid that 'plastic pop' sound",
    "no over-tight editing — let air in between notes",
    "don't push loudness to modern-streaming levels",
    "avoid sonic sterility — some grit is welcome",
    "no cartoonish 'radio ready' feel",
    "don't let compression wash out the groove",
    "avoid an 'obvious mix' — make it feel like it always sounded that way",
)
